# Production Worker (default environment)
# Deploys with: wrangler deploy
name = "mastermarat-api"
main = "src/worker.js"
compatibility_date = "2024-01-01"
route = "api.mastermarat.com/*"
vars = { ENVIRONMENT = "production" }

[[r2_buckets]]
binding = "R2"
bucket_name = "mastermarat-videos"

# --------------------------------------------------

# Development Environment
# Deploys with: wrangler deploy --env dev
[env.dev]
name = "mastermarat-api-dev"
route = "api-dev.mastermarat.com/*"
vars = { ENVIRONMENT = "development" }

[[env.dev.r2_buckets]]
binding = "R2"
bucket_name = "mastermarat-videos"