name = "mastermarat-api"
main = "src/worker-new.js"
compatibility_date = "2024-07-01"

# R2 bucket binding
[[r2_buckets]]
binding = "R2"
bucket_name = "mastermarat-videos"

# Production environment
[env.production]
name = "mastermarat-api"
route = { pattern = "api.mastermarat.com/*", zone_name = "mastermarat.com" }

[env.production.vars]
ENVIRONMENT = "production"

# Development environment
[env.dev]
name = "mastermarat-api-dev"
route = { pattern = "api-dev.mastermarat.com/*", zone_name = "mastermarat.com" }

[env.dev.vars]
ENVIRONMENT = "development"
