name = "mastermarat-api"
main = "src/worker.js"
compatibility_date = "2024-01-01"

# Глобальные настройки
vars = { ENVIRONMENT = "development" }

# R2 bucket binding
[[r2_buckets]]
binding = "R2"
bucket_name = "mastermarat-videos"

# Development environment (по умолчанию)
[env.development]
vars = { ENVIRONMENT = "development" }

[[env.development.r2_buckets]]
binding = "R2"
bucket_name = "mastermarat-videos"

# Production environment
[env.production]
# ИСПРАВЛЕНО: убрали wildcard и path из route
route = "api.mastermarat.com"
vars = { ENVIRONMENT = "production" }

[[env.production.r2_buckets]]
binding = "R2"
bucket_name = "mastermarat-videos"